#!/bin/sh

# generate menu
    xdgmenumaker -f icewm > ~/.icewm/menu

# picom
    picom &

# set background image
    nitrogen --restore &

# volume control for systray
    volumeicon &

# start network manager
    sleep 1 &&
    nm-applet &

# enable bluetooth applet
#    sleep 1 &&
#    blueman-applet &!

# enable screensaver
    xscreensaver -nosplash &

# start redshift
#    redshift &

# allow notifications
    /usr/lib/notification-daemon-1.0/notification-daemon &
    
# enable lockscreen
#    exec xautolock -detectsleep -time 15 -locker "i3lock -n -i /home/user/lockscreen.png" -killtime 20 -killer "systemctl suspend" #lock after inactivity and then sleep
