#!/bin/sh

# start network manager
#    sleep 1 &&
#    nm-applet &

# enable bluetooth applet
#    sleep 1 &&
#    blueman-applet &!

# enable screensaver
#    xscreensaver -nosplash &

# start redshift
#    redshift &

# enable lockscreen
#    exec xautolock -detectsleep -time 15 -locker "i3lock -n -i /home/user/lockscreen.png" -killtime 20 -killer "systemctl suspend" #lock after inactivity and then sleep

# allow notifications
#    /usr/lib/notification-daemon-1.0/notification-daemon &

nitrogen --restore &
xcompmgr &
lxpolkit &
xsetroot -cursor_name left_ptr &
