#!/bin/bash

background="#2e3440"

Workspaces() {
	desktops=$(bspc query -D --names)
  focused=$(bspc query -D --names -d focused)

	for desktop in $desktops; do
		desktop=$(echo "$desktop")
		nodes=$(bspc query -N -d $desktop)

		if [ ! -z "$nodes" ]; then
			desktops=$(echo $desktops | sed "s/$desktop/%{F#d08770}$desktop%{F-}/")
    fi

  done
  desktops=$(echo $desktops | sed "s/$focused/%{B$background}%{+u}_$focused\_%{-u}%{B-}/")

  echo $desktops | sed "s/_/ /g"
}

ActiveWindow() {
	printf "$(xdotool getwindowfocus getwindowname)"
}

Memory() {
  mem=`free | awk '/Mem/ {printf "%dM/%dM\n", $3 / 1024.0, $2 / 1024.0 }'`
  echo -e "| MEM: $mem"
}

Cpu() {
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  echo -e "| CPU: $cpu%"
}

Volume() {
    vol=`amixer get Master | awk -F'[][]' 'END{ print $4":"$2 }' | sed 's/on://g'`
    echo -e "VOL: $vol"
}

Clock() {
        DATETIME=$(date "+%a %b %d, %T")

        echo -n "[$DATETIME]"
}

SLEEP_SEC=1

while :; do
	echo "%{l} $(Workspaces) - $(ActiveWindow) %{r} $(Volume) $(Cpu) $(Memory) $(Clock)"
	sleep $SLEEP_SEC
done
