#!/bin/sh

killall -q lemonbar
killall -q $HOME/.config/lemonbar/bar

$HOME/.config/lemonbar/bar | lemonbar -p -F "#d8dee9" -B "#2e3440" -U "#ebcb8b" -u 2 \
	-f '-misc-fixed-*-*-*-*-13-*-*-*-*-*-*-*' | $sh
