#!/bin/sh

[ -e ~/.profile ] && . ~/.profile

pgrep -x sxhkd > /dev/null || sxhkd &
set -U SXHKD_SHELL sh &
pgrep -x panel > /dev/null || $HOME/.config/bspwm/panel/panel &
nitrogen --restore &
xcompmgr &
lxpolkit &
xsetroot -cursor_name left_ptr &
wmname LG3D &
#$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

#overlapping borders
BW=3
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done

#external rules
bspc config external_rules_command "$(which external_rules)"

#bspc config border_width         2
#bspc config window_gap          12

bspc config split_ratio          0.52
bspc config click_to_focus       true
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_by_distance        true
bspc config focus_follows_pointer    true
bspc config history_aware_focus      true

bspc config normal_border_color        "#4c566a"
bspc config active_border_color        "#3b4252"
bspc config focused_border_color       "#5e81ac"
bspc config presel_feedback_color      "#5e81ac"
bspc config urgent_border_color        "#bf616a"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
