#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
set -U SXHKD_SHELL sh &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
picom &
lxpolkit &
urxvtd -q -o -f &
emacs --daemon &
xsetroot -cursor_name left_ptr &
wmname LG3D &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width             2
bspc config window_gap               5

bspc config split_ratio              0.52
bspc config click_to_focus           false
bspc config borderless_monocle       false
bspc config gapless_monocle          false
bspc config focus_follows_pointer    true

bspc config normal_border_color        "#4c566a"
bspc config active_border_color        "#3b4252"
bspc config focused_border_color       "#5e81ac"
bspc config presel_feedback_color      "#5e81ac"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
